// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

edition = "2023";

package clustermesh;
option go_package = "github.com/cilium/cilium/api/v1/clustermesh";

import "google/protobuf/go_features.proto";
option features.(pb.go).api_level = API_OPAQUE;

message Backend {
  string address = 1;
  uint32 conditions = 2;

  // Zone info
  uint32 zone_index = 3;
  repeated uint32 hints_for_zones_indexes = 4;

  string hostname = 5;
}

enum L4Type {
  L4_TYPE_UNSPECIFIED = 0;
  L4_TYPE_TCP = 1;
  L4_TYPE_UDP = 2;
  L4_TYPE_SCTP = 3;
}

message Port {
  L4Type protocol = 1;
  uint32 port = 2;
  // Port name can be looked up in the `port_names_table` in the ClusterService message
  uint32 name_index = 3;
}

message EndpointSlice {
  repeated Port ports = 1;
  repeated Backend backends = 2;
  string endpoint_slice_name = 3;
}

// ClusterService represents a service definition within a cluster
message ClusterService {
  string cluster = 1;
  uint32 cluster_id = 2;
  string namespace = 3;
  string name = 4;

  // String Interning Tables to reduce per backend size
  repeated string port_names_table = 5;
  repeated string zone_names_table = 6;

  repeated EndpointSlice endpoint_slices = 7;
}
