// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.1
// source: clustermesh/clusterservice.proto

package clustermesh

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type L4Type int32

const (
	L4Type_L4_TYPE_UNSPECIFIED L4Type = 0
	L4Type_L4_TYPE_TCP         L4Type = 1
	L4Type_L4_TYPE_UDP         L4Type = 2
	L4Type_L4_TYPE_SCTP        L4Type = 3
)

// Enum value maps for L4Type.
var (
	L4Type_name = map[int32]string{
		0: "L4_TYPE_UNSPECIFIED",
		1: "L4_TYPE_TCP",
		2: "L4_TYPE_UDP",
		3: "L4_TYPE_SCTP",
	}
	L4Type_value = map[string]int32{
		"L4_TYPE_UNSPECIFIED": 0,
		"L4_TYPE_TCP":         1,
		"L4_TYPE_UDP":         2,
		"L4_TYPE_SCTP":        3,
	}
)

func (x L4Type) Enum() *L4Type {
	p := new(L4Type)
	*p = x
	return p
}

func (x L4Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L4Type) Descriptor() protoreflect.EnumDescriptor {
	return file_clustermesh_clusterservice_proto_enumTypes[0].Descriptor()
}

func (L4Type) Type() protoreflect.EnumType {
	return &file_clustermesh_clusterservice_proto_enumTypes[0]
}

func (x L4Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Backend struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Address              isBackend_Address      `protobuf_oneof:"address"`
	xxx_hidden_Conditions           uint32                 `protobuf:"varint,3,opt,name=conditions"`
	xxx_hidden_ZoneIndex            uint32                 `protobuf:"varint,4,opt,name=zone_index,json=zoneIndex"`
	xxx_hidden_HintsForZonesIndexes []uint32               `protobuf:"varint,5,rep,packed,name=hints_for_zones_indexes,json=hintsForZonesIndexes"`
	xxx_hidden_Hostname             *string                `protobuf:"bytes,6,opt,name=hostname"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *Backend) Reset() {
	*x = Backend{}
	mi := &file_clustermesh_clusterservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_clustermesh_clusterservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Backend) GetV4() uint32 {
	if x != nil {
		if x, ok := x.xxx_hidden_Address.(*backend_V4); ok {
			return x.V4
		}
	}
	return 0
}

func (x *Backend) GetV6() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Address.(*backend_V6); ok {
			return x.V6
		}
	}
	return nil
}

func (x *Backend) GetConditions() uint32 {
	if x != nil {
		return x.xxx_hidden_Conditions
	}
	return 0
}

func (x *Backend) GetZoneIndex() uint32 {
	if x != nil {
		return x.xxx_hidden_ZoneIndex
	}
	return 0
}

func (x *Backend) GetHintsForZonesIndexes() []uint32 {
	if x != nil {
		return x.xxx_hidden_HintsForZonesIndexes
	}
	return nil
}

func (x *Backend) GetHostname() string {
	if x != nil {
		if x.xxx_hidden_Hostname != nil {
			return *x.xxx_hidden_Hostname
		}
		return ""
	}
	return ""
}

func (x *Backend) SetV4(v uint32) {
	x.xxx_hidden_Address = &backend_V4{v}
}

func (x *Backend) SetV6(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Address = &backend_V6{v}
}

func (x *Backend) SetConditions(v uint32) {
	x.xxx_hidden_Conditions = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *Backend) SetZoneIndex(v uint32) {
	x.xxx_hidden_ZoneIndex = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *Backend) SetHintsForZonesIndexes(v []uint32) {
	x.xxx_hidden_HintsForZonesIndexes = v
}

func (x *Backend) SetHostname(v string) {
	x.xxx_hidden_Hostname = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *Backend) HasAddress() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Address != nil
}

func (x *Backend) HasV4() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Address.(*backend_V4)
	return ok
}

func (x *Backend) HasV6() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Address.(*backend_V6)
	return ok
}

func (x *Backend) HasConditions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Backend) HasZoneIndex() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Backend) HasHostname() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Backend) ClearAddress() {
	x.xxx_hidden_Address = nil
}

func (x *Backend) ClearV4() {
	if _, ok := x.xxx_hidden_Address.(*backend_V4); ok {
		x.xxx_hidden_Address = nil
	}
}

func (x *Backend) ClearV6() {
	if _, ok := x.xxx_hidden_Address.(*backend_V6); ok {
		x.xxx_hidden_Address = nil
	}
}

func (x *Backend) ClearConditions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Conditions = 0
}

func (x *Backend) ClearZoneIndex() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ZoneIndex = 0
}

func (x *Backend) ClearHostname() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Hostname = nil
}

const Backend_Address_not_set_case case_Backend_Address = 0
const Backend_V4_case case_Backend_Address = 1
const Backend_V6_case case_Backend_Address = 2

func (x *Backend) WhichAddress() case_Backend_Address {
	if x == nil {
		return Backend_Address_not_set_case
	}
	switch x.xxx_hidden_Address.(type) {
	case *backend_V4:
		return Backend_V4_case
	case *backend_V6:
		return Backend_V6_case
	default:
		return Backend_Address_not_set_case
	}
}

type Backend_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Address:
	V4 *uint32
	V6 []byte
	// -- end of xxx_hidden_Address
	Conditions *uint32
	// Zone info
	ZoneIndex            *uint32
	HintsForZonesIndexes []uint32
	Hostname             *string
}

func (b0 Backend_builder) Build() *Backend {
	m0 := &Backend{}
	b, x := &b0, m0
	_, _ = b, x
	if b.V4 != nil {
		x.xxx_hidden_Address = &backend_V4{*b.V4}
	}
	if b.V6 != nil {
		x.xxx_hidden_Address = &backend_V6{b.V6}
	}
	if b.Conditions != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Conditions = *b.Conditions
	}
	if b.ZoneIndex != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_ZoneIndex = *b.ZoneIndex
	}
	x.xxx_hidden_HintsForZonesIndexes = b.HintsForZonesIndexes
	if b.Hostname != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Hostname = b.Hostname
	}
	return m0
}

type case_Backend_Address protoreflect.FieldNumber

func (x case_Backend_Address) String() string {
	md := file_clustermesh_clusterservice_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isBackend_Address interface {
	isBackend_Address()
}

type backend_V4 struct {
	V4 uint32 `protobuf:"fixed32,1,opt,name=v4,oneof"`
}

type backend_V6 struct {
	V6 []byte `protobuf:"bytes,2,opt,name=v6,oneof"`
}

func (*backend_V4) isBackend_Address() {}

func (*backend_V6) isBackend_Address() {}

type Port struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Protocol    L4Type                 `protobuf:"varint,1,opt,name=protocol,enum=clustermesh.L4Type"`
	xxx_hidden_Port        uint32                 `protobuf:"varint,2,opt,name=port"`
	xxx_hidden_NameIndex   uint32                 `protobuf:"varint,3,opt,name=name_index,json=nameIndex"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_clustermesh_clusterservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_clustermesh_clusterservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Port) GetProtocol() L4Type {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Protocol
		}
	}
	return L4Type_L4_TYPE_UNSPECIFIED
}

func (x *Port) GetPort() uint32 {
	if x != nil {
		return x.xxx_hidden_Port
	}
	return 0
}

func (x *Port) GetNameIndex() uint32 {
	if x != nil {
		return x.xxx_hidden_NameIndex
	}
	return 0
}

func (x *Port) SetProtocol(v L4Type) {
	x.xxx_hidden_Protocol = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Port) SetPort(v uint32) {
	x.xxx_hidden_Port = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Port) SetNameIndex(v uint32) {
	x.xxx_hidden_NameIndex = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Port) HasProtocol() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Port) HasPort() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Port) HasNameIndex() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Port) ClearProtocol() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Protocol = L4Type_L4_TYPE_UNSPECIFIED
}

func (x *Port) ClearPort() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Port = 0
}

func (x *Port) ClearNameIndex() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_NameIndex = 0
}

type Port_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Protocol *L4Type
	Port     *uint32
	// Port name can be looked up in the `port_names_table` in the ClusterService message
	NameIndex *uint32
}

func (b0 Port_builder) Build() *Port {
	m0 := &Port{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Protocol != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Protocol = *b.Protocol
	}
	if b.Port != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Port = *b.Port
	}
	if b.NameIndex != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_NameIndex = *b.NameIndex
	}
	return m0
}

type Endpoint struct {
	state                               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ports                    *[]*Port               `protobuf:"bytes,1,rep,name=ports"`
	xxx_hidden_Backends                 *[]*Backend            `protobuf:"bytes,2,rep,name=backends"`
	xxx_hidden_EndpointsName            *string                `protobuf:"bytes,3,opt,name=endpoints_name,json=endpointsName"`
	xxx_hidden_EndpointsResourceVersion *string                `protobuf:"bytes,4,opt,name=endpoints_resource_version,json=endpointsResourceVersion"`
	XXX_raceDetectHookData              protoimpl.RaceDetectHookData
	XXX_presence                        [1]uint32
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_clustermesh_clusterservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_clustermesh_clusterservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Endpoint) GetPorts() []*Port {
	if x != nil {
		if x.xxx_hidden_Ports != nil {
			return *x.xxx_hidden_Ports
		}
	}
	return nil
}

func (x *Endpoint) GetBackends() []*Backend {
	if x != nil {
		if x.xxx_hidden_Backends != nil {
			return *x.xxx_hidden_Backends
		}
	}
	return nil
}

func (x *Endpoint) GetEndpointsName() string {
	if x != nil {
		if x.xxx_hidden_EndpointsName != nil {
			return *x.xxx_hidden_EndpointsName
		}
		return ""
	}
	return ""
}

func (x *Endpoint) GetEndpointsResourceVersion() string {
	if x != nil {
		if x.xxx_hidden_EndpointsResourceVersion != nil {
			return *x.xxx_hidden_EndpointsResourceVersion
		}
		return ""
	}
	return ""
}

func (x *Endpoint) SetPorts(v []*Port) {
	x.xxx_hidden_Ports = &v
}

func (x *Endpoint) SetBackends(v []*Backend) {
	x.xxx_hidden_Backends = &v
}

func (x *Endpoint) SetEndpointsName(v string) {
	x.xxx_hidden_EndpointsName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *Endpoint) SetEndpointsResourceVersion(v string) {
	x.xxx_hidden_EndpointsResourceVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *Endpoint) HasEndpointsName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Endpoint) HasEndpointsResourceVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Endpoint) ClearEndpointsName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_EndpointsName = nil
}

func (x *Endpoint) ClearEndpointsResourceVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_EndpointsResourceVersion = nil
}

type Endpoint_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ports                    []*Port
	Backends                 []*Backend
	EndpointsName            *string
	EndpointsResourceVersion *string
}

func (b0 Endpoint_builder) Build() *Endpoint {
	m0 := &Endpoint{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ports = &b.Ports
	x.xxx_hidden_Backends = &b.Backends
	if b.EndpointsName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_EndpointsName = b.EndpointsName
	}
	if b.EndpointsResourceVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_EndpointsResourceVersion = b.EndpointsResourceVersion
	}
	return m0
}

// ClusterService represents a service definition within a cluster
type ClusterService struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cluster        *string                `protobuf:"bytes,1,opt,name=cluster"`
	xxx_hidden_ClusterId      uint32                 `protobuf:"varint,2,opt,name=cluster_id,json=clusterId"`
	xxx_hidden_Namespace      *string                `protobuf:"bytes,3,opt,name=namespace"`
	xxx_hidden_Name           *string                `protobuf:"bytes,4,opt,name=name"`
	xxx_hidden_PortNamesTable []string               `protobuf:"bytes,5,rep,name=port_names_table,json=portNamesTable"`
	xxx_hidden_ZoneNamesTable []string               `protobuf:"bytes,6,rep,name=zone_names_table,json=zoneNamesTable"`
	xxx_hidden_Endpoints      *[]*Endpoint           `protobuf:"bytes,7,rep,name=endpoints"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ClusterService) Reset() {
	*x = ClusterService{}
	mi := &file_clustermesh_clusterservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterService) ProtoMessage() {}

func (x *ClusterService) ProtoReflect() protoreflect.Message {
	mi := &file_clustermesh_clusterservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ClusterService) GetCluster() string {
	if x != nil {
		if x.xxx_hidden_Cluster != nil {
			return *x.xxx_hidden_Cluster
		}
		return ""
	}
	return ""
}

func (x *ClusterService) GetClusterId() uint32 {
	if x != nil {
		return x.xxx_hidden_ClusterId
	}
	return 0
}

func (x *ClusterService) GetNamespace() string {
	if x != nil {
		if x.xxx_hidden_Namespace != nil {
			return *x.xxx_hidden_Namespace
		}
		return ""
	}
	return ""
}

func (x *ClusterService) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *ClusterService) GetPortNamesTable() []string {
	if x != nil {
		return x.xxx_hidden_PortNamesTable
	}
	return nil
}

func (x *ClusterService) GetZoneNamesTable() []string {
	if x != nil {
		return x.xxx_hidden_ZoneNamesTable
	}
	return nil
}

func (x *ClusterService) GetEndpoints() []*Endpoint {
	if x != nil {
		if x.xxx_hidden_Endpoints != nil {
			return *x.xxx_hidden_Endpoints
		}
	}
	return nil
}

func (x *ClusterService) SetCluster(v string) {
	x.xxx_hidden_Cluster = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *ClusterService) SetClusterId(v uint32) {
	x.xxx_hidden_ClusterId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *ClusterService) SetNamespace(v string) {
	x.xxx_hidden_Namespace = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *ClusterService) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *ClusterService) SetPortNamesTable(v []string) {
	x.xxx_hidden_PortNamesTable = v
}

func (x *ClusterService) SetZoneNamesTable(v []string) {
	x.xxx_hidden_ZoneNamesTable = v
}

func (x *ClusterService) SetEndpoints(v []*Endpoint) {
	x.xxx_hidden_Endpoints = &v
}

func (x *ClusterService) HasCluster() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ClusterService) HasClusterId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ClusterService) HasNamespace() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ClusterService) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ClusterService) ClearCluster() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Cluster = nil
}

func (x *ClusterService) ClearClusterId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ClusterId = 0
}

func (x *ClusterService) ClearNamespace() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Namespace = nil
}

func (x *ClusterService) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Name = nil
}

type ClusterService_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Cluster   *string
	ClusterId *uint32
	Namespace *string
	Name      *string
	// String Interning Tables
	PortNamesTable []string
	ZoneNamesTable []string
	Endpoints      []*Endpoint
}

func (b0 ClusterService_builder) Build() *ClusterService {
	m0 := &ClusterService{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Cluster != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Cluster = b.Cluster
	}
	if b.ClusterId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_ClusterId = *b.ClusterId
	}
	if b.Namespace != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Namespace = b.Namespace
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Name = b.Name
	}
	x.xxx_hidden_PortNamesTable = b.PortNamesTable
	x.xxx_hidden_ZoneNamesTable = b.ZoneNamesTable
	x.xxx_hidden_Endpoints = &b.Endpoints
	return m0
}

var File_clustermesh_clusterservice_proto protoreflect.FileDescriptor

const file_clustermesh_clusterservice_proto_rawDesc = "" +
	"\n" +
	" clustermesh/clusterservice.proto\x12\vclustermesh\x1a!google/protobuf/go_features.proto\"\xca\x01\n" +
	"\aBackend\x12\x10\n" +
	"\x02v4\x18\x01 \x01(\aH\x00R\x02v4\x12\x10\n" +
	"\x02v6\x18\x02 \x01(\fH\x00R\x02v6\x12\x1e\n" +
	"\n" +
	"conditions\x18\x03 \x01(\rR\n" +
	"conditions\x12\x1d\n" +
	"\n" +
	"zone_index\x18\x04 \x01(\rR\tzoneIndex\x125\n" +
	"\x17hints_for_zones_indexes\x18\x05 \x03(\rR\x14hintsForZonesIndexes\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostnameB\t\n" +
	"\aaddress\"j\n" +
	"\x04Port\x12/\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x13.clustermesh.L4TypeR\bprotocol\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1d\n" +
	"\n" +
	"name_index\x18\x03 \x01(\rR\tnameIndex\"\xca\x01\n" +
	"\bEndpoint\x12'\n" +
	"\x05ports\x18\x01 \x03(\v2\x11.clustermesh.PortR\x05ports\x120\n" +
	"\bbackends\x18\x02 \x03(\v2\x14.clustermesh.BackendR\bbackends\x12%\n" +
	"\x0eendpoints_name\x18\x03 \x01(\tR\rendpointsName\x12<\n" +
	"\x1aendpoints_resource_version\x18\x04 \x01(\tR\x18endpointsResourceVersion\"\x84\x02\n" +
	"\x0eClusterService\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\rR\tclusterId\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12(\n" +
	"\x10port_names_table\x18\x05 \x03(\tR\x0eportNamesTable\x12(\n" +
	"\x10zone_names_table\x18\x06 \x03(\tR\x0ezoneNamesTable\x123\n" +
	"\tendpoints\x18\a \x03(\v2\x15.clustermesh.EndpointR\tendpoints*U\n" +
	"\x06L4Type\x12\x17\n" +
	"\x13L4_TYPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vL4_TYPE_TCP\x10\x01\x12\x0f\n" +
	"\vL4_TYPE_UDP\x10\x02\x12\x10\n" +
	"\fL4_TYPE_SCTP\x10\x03B5Z+github.com/cilium/cilium/api/v1/clustermesh\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_clustermesh_clusterservice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clustermesh_clusterservice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_clustermesh_clusterservice_proto_goTypes = []any{
	(L4Type)(0),            // 0: clustermesh.L4Type
	(*Backend)(nil),        // 1: clustermesh.Backend
	(*Port)(nil),           // 2: clustermesh.Port
	(*Endpoint)(nil),       // 3: clustermesh.Endpoint
	(*ClusterService)(nil), // 4: clustermesh.ClusterService
}
var file_clustermesh_clusterservice_proto_depIdxs = []int32{
	0, // 0: clustermesh.Port.protocol:type_name -> clustermesh.L4Type
	2, // 1: clustermesh.Endpoint.ports:type_name -> clustermesh.Port
	1, // 2: clustermesh.Endpoint.backends:type_name -> clustermesh.Backend
	3, // 3: clustermesh.ClusterService.endpoints:type_name -> clustermesh.Endpoint
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_clustermesh_clusterservice_proto_init() }
func file_clustermesh_clusterservice_proto_init() {
	if File_clustermesh_clusterservice_proto != nil {
		return
	}
	file_clustermesh_clusterservice_proto_msgTypes[0].OneofWrappers = []any{
		(*backend_V4)(nil),
		(*backend_V6)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clustermesh_clusterservice_proto_rawDesc), len(file_clustermesh_clusterservice_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clustermesh_clusterservice_proto_goTypes,
		DependencyIndexes: file_clustermesh_clusterservice_proto_depIdxs,
		EnumInfos:         file_clustermesh_clusterservice_proto_enumTypes,
		MessageInfos:      file_clustermesh_clusterservice_proto_msgTypes,
	}.Build()
	File_clustermesh_clusterservice_proto = out.File
	file_clustermesh_clusterservice_proto_goTypes = nil
	file_clustermesh_clusterservice_proto_depIdxs = nil
}
